### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'METADATA'

### ISSUE THREAD

**Issue by mxochicale** [UCL-RITS/mkdocs-rc-docs#42]
Hi,

I am trying to create a conda environment in myriad with `conda env create -f vem.yml`, where the content of `vem.yml` is: 
```
name: medisynVE
channels:
  -python
  - conda-forge
dependencies:
  - pip
  - pip:
    - pytorch
    - torchvision
    - open-clip-torch
    - numpy
    - matplotlib
    - opencv-python
    - wandb
    - tqdm
    - notebook
    - jupyter
    - seaborn 
    - scikit-image
    - nibabel
    - pillow
    - datasets
    - diffusers
    - torchmetrics
    - monai
    - accelerate
    - torch-fidelity
```
Then I get this errors:

*  ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'METADATA'
```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'METADATA'
Consider using the `--user` option or check the permissions.
```

* Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
```
n, nbclient, ipykernel, diffusers, argon2-cffi, qtconsole, open-clip-torch, nbconvert, jupyter-events, jupyter-console, ipywidgets, datasets, jupyter-server, notebook-shim, nbclassic, notebook, jupyter
  Running setup.py install for pytorch ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pytorch did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1bpr32tm/pytorch_e02cb7bf79d54d4a9e4310933aaaab58/setup.py", line 11, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure


```
Then, I made this changes to vem.yml:
```
name: medisynVE
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - torch
    - torchvision
    - open-clip-torch
    - numpy
    - matplotlib
    - opencv-python
    - wandb
    - tqdm
    - notebook
    - jupyter
    - seaborn 
    - scikit-image
    - nibabel
    - pillow
    - datasets
    - diffusers
    - torchmetrics
    - monai
    - accelerate
    - torch-fidelity
```
but got:

```
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.9
    Uninstalling urllib3-1.26.9:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'METADATA'
Consider using the `--user` option or check the permissions.


```

Any suggestions? 

Thanks

**Comment by heatherkellyucl** [comment]
This is not the correct place to ask for support (rc-support@ucl.ac.uk or in Slack as internal to ARC) but you need to include `--user` for a user install in the `conda env create` command.
